import { compose, createStore } from "redux";

const ReactReduxDevTools =
  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__();

/**
 * État initial pour la gestion des employés.
 * @typedef {Object} InitialState
 * @property {Array<Object>} employees - Liste des employés.
 * @property {string} employees[].firstName - Prénom de l'employé.
 * @property {string} employees[].lastName - Nom de l'employé.
 * @property {string} employees[].street - Adresse de l'employé.
 * @property {string} employees[].city - Ville de l'employé.
 * @property {string} employees[].zipCode - Code postal de l'employé.
 * @property {string} employees[].birthDate - Date de naissance de l'employé (format : JJ/MM/AAAA).
 * @property {string} employees[].startDate - Date de début d'emploi de l'employé (format : JJ/MM/AAAA).
 * @property {string} employees[].department - Service auquel l'employé appartient.
 * @property {string} employees[].state - État/région de l'employé.
 */

/**
 * État initial de l'application.
 * @type {InitialState}
 */
const initialState = {
  employees: [
    {
      firstName: "Gillan",
      lastName: "Blazey",
      street: "0588 Brentwood Park",
      city: "Hagondange",
      zipCode: "57304 CEDEX",
      birthDate: "03/12/1990",
      startDate: "04/03/2023",
      department: "Legal",
      state: "Lorraine",
    },
    {
      firstName: "Sibylla",
      lastName: "Greggersen",
      street: "0 Warbler Parkway",
      city: "Carcassonne",
      zipCode: "11860 CEDEX 9",
      birthDate: "02/06/1962",
      startDate: "22/05/2023",
      department: "Sales",
      state: "Languedoc-Roussillon",
    },
    {
      firstName: "Gabriele",
      lastName: "Cready",
      street: "45086 Cody Crossing",
      city: "Reims",
      zipCode: "51054 CEDEX",
      birthDate: "17/07/2006",
      startDate: "03/12/2022",
      department: "Marketing",
      state: "Champagne-Ardenne",
    },
    {
      firstName: "Diane",
      lastName: "Peeke",
      street: "713 Walton Terrace",
      city: "Tarbes",
      zipCode: "65004 CEDEX",
      birthDate: "05/04/2000",
      startDate: "20/03/2023",
      department: "Sales",
      state: "Midi-Pyrénées",
    },
    {
      firstName: "Adair",
      lastName: "Logan",
      street: "3962 Fuller Hill",
      city: "Mont-de-Marsan",
      zipCode: "40025 CEDEX",
      birthDate: "28/10/1988",
      startDate: "11/01/2023",
      department: "Human Resources",
      state: "Aquitaine",
    },
    {
      firstName: "Philomena",
      lastName: "Grout",
      street: "9685 Banding Parkway",
      city: "Angoulême",
      zipCode: "16904 CEDEX 9",
      birthDate: "23/01/1992",
      startDate: "24/12/2022",
      department: "Engineering",
      state: "Poitou-Charentes",
    },
    {
      firstName: "Corri",
      lastName: "Janosevic",
      street: "32046 Duke Parkway",
      city: "Orly aérogare",
      zipCode: "94542 CEDEX",
      birthDate: "04/01/1996",
      startDate: "13/03/2023",
      department: "Legal",
      state: "Île-de-France",
    },
    {
      firstName: "Ogden",
      lastName: "Libbe",
      street: "43343 Talmadge Crossing",
      city: "Villeneuve-d'Ascq",
      zipCode: "59663 CEDEX",
      birthDate: "17/09/1992",
      startDate: "21/08/2022",
      department: "Marketing",
      state: "Nord-Pas-de-Calais",
    },
    {
      firstName: "Lauren",
      lastName: "Lothlorien",
      street: "9173 Saint Paul Avenue",
      city: "Montfort-sur-Meu",
      zipCode: "35164 CEDEX",
      birthDate: "07/07/1971",
      startDate: "30/11/2022",
      department: "Human Resources",
      state: "Bretagne",
    },
    {
      firstName: "Meghan",
      lastName: "Fairebrother",
      street: "798 Helena Alley",
      city: "Paris La Défense",
      zipCode: "92056 CEDEX",
      birthDate: "24/07/1971",
      startDate: "17/06/2023",
      department: "Legal",
      state: "Île-de-France",
    },
    {
      firstName: "Dedie",
      lastName: "Blaszczak",
      street: "861 Forest Dale Pass",
      city: "Saint-Denis",
      zipCode: "93285 CEDEX",
      birthDate: "26/03/1979",
      startDate: "24/01/2023",
      department: "Marketing",
      state: "Île-de-France",
    },
    {
      firstName: "Gray",
      lastName: "Boyer",
      street: "5 Coleman Junction",
      city: "Vagney",
      zipCode: "88125 CEDEX",
      birthDate: "14/10/2003",
      startDate: "09/06/2023",
      department: "Marketing",
      state: "Lorraine",
    },
    {
      firstName: "Gertrud",
      lastName: "Presho",
      street: "47 Victoria Plaza",
      city: "Thiais",
      zipCode: "94657 CEDEX",
      birthDate: "08/02/1984",
      startDate: "25/04/2023",
      department: "Sales",
      state: "Île-de-France",
    },
    {
      firstName: "Kaleb",
      lastName: "Loughman",
      street: "6032 Thierer Parkway",
      city: "Toulouse",
      zipCode: "31069 CEDEX 7",
      birthDate: "26/09/1961",
      startDate: "03/11/2022",
      department: "Marketing",
      state: "Midi-Pyrénées",
    },
    {
      firstName: "Jeniece",
      lastName: "Petrasch",
      street: "49 Spohn Alley",
      city: "Seynod",
      zipCode: "74604 CEDEX",
      birthDate: "02/11/2009",
      startDate: "26/04/2023",
      department: "Engineering",
      state: "Rhône-Alpes",
    },
    {
      firstName: "August",
      lastName: "McGeaney",
      street: "49 Petterle Circle",
      city: "Poligny",
      zipCode: "39804 CEDEX",
      birthDate: "18/12/1986",
      startDate: "31/07/2023",
      department: "Sales",
      state: "Franche-Comté",
    },
    {
      firstName: "Talyah",
      lastName: "Ovenell",
      street: "5512 Tennessee Alley",
      city: "Caen",
      zipCode: "14018 CEDEX 2",
      birthDate: "16/11/1998",
      startDate: "08/06/2023",
      department: "Legal",
      state: "Basse-Normandie",
    },
    {
      firstName: "Emyle",
      lastName: "Poytres",
      street: "554 Lighthouse Bay Road",
      city: "Nevers",
      zipCode: "58028 CEDEX",
      birthDate: "10/10/1987",
      startDate: "20/07/2023",
      department: "Sales",
      state: "Bourgogne",
    },
    {
      firstName: "Des",
      lastName: "Cutford",
      street: "28 Blackbird Junction",
      city: "Toulouse",
      zipCode: "31085 CEDEX 2",
      birthDate: "25/12/1982",
      startDate: "10/01/2023",
      department: "Engineering",
      state: "Midi-Pyrénées",
    },
    {
      firstName: "Carolan",
      lastName: "Tassell",
      street: "70 Autumn Leaf Park",
      city: "La Roche-sur-Yon",
      zipCode: "85009 CEDEX",
      birthDate: "07/11/2006",
      startDate: "13/12/2022",
      department: "Engineering",
      state: "Pays de la Loire",
    },
    {
      firstName: "Chaddie",
      lastName: "Bridgland",
      street: "059 Towne Trail",
      city: "Périgueux",
      zipCode: "24053 CEDEX",
      birthDate: "12/01/2002",
      startDate: "09/06/2023",
      department: "Legal",
      state: "Aquitaine",
    },
    {
      firstName: "Ephrem",
      lastName: "Basire",
      street: "4685 Meadow Ridge Way",
      city: "Paris 19",
      zipCode: "75934 CEDEX 19",
      birthDate: "27/02/2010",
      startDate: "09/02/2023",
      department: "Marketing",
      state: "Île-de-France",
    },
    {
      firstName: "Winfield",
      lastName: "Meran",
      street: "98673 Kim Way",
      city: "Le Havre",
      zipCode: "76600",
      birthDate: "22/10/1998",
      startDate: "01/02/2023",
      department: "Human Resources",
      state: "Haute-Normandie",
    },
    {
      firstName: "Kellyann",
      lastName: "Naton",
      street: "97 Stone Corner Street",
      city: "Vitrolles",
      zipCode: "13841 CEDEX",
      birthDate: "09/11/1981",
      startDate: "20/11/2022",
      department: "Marketing",
      state: "Provence-Alpes-Côte d'Azur",
    },
    {
      firstName: "Bette",
      lastName: "O'Doherty",
      street: "8 Thierer Junction",
      city: "Cergy-Pontoise",
      zipCode: "95611 CEDEX",
      birthDate: "17/08/1977",
      startDate: "03/01/2023",
      department: "Human Resources",
      state: "Île-de-France",
    },
    {
      firstName: "Lianne",
      lastName: "Lamshead",
      street: "4 Haas Crossing",
      city: "Amiens",
      zipCode: "80031 CEDEX 1",
      birthDate: "14/10/1974",
      startDate: "16/02/2023",
      department: "Engineering",
      state: "Picardie",
    },
    {
      firstName: "Neill",
      lastName: "Reilingen",
      street: "49149 Rigney Lane",
      city: "Saint-Pierre-Montlimart",
      zipCode: "49117 CEDEX",
      birthDate: "03/02/1992",
      startDate: "29/01/2023",
      department: "Sales",
      state: "Pays de la Loire",
    },
    {
      firstName: "Iona",
      lastName: "MacGilmartin",
      street: "67 Golf Parkway",
      city: "Nantes",
      zipCode: "44004 CEDEX 1",
      birthDate: "19/10/1982",
      startDate: "18/09/2022",
      department: "Human Resources",
      state: "Pays de la Loire",
    },
    {
      firstName: "Thayne",
      lastName: "Northway",
      street: "195 Sunnyside Junction",
      city: "Saint-Quentin",
      zipCode: "02323 CEDEX",
      birthDate: "10/02/1962",
      startDate: "17/08/2022",
      department: "Human Resources",
      state: "Picardie",
    },
    {
      firstName: "Yettie",
      lastName: "Downie",
      street: "5837 Cottonwood Circle",
      city: "Brest",
      zipCode: "29825 CEDEX 9",
      birthDate: "17/02/1998",
      startDate: "10/09/2022",
      department: "Sales",
      state: "Bretagne",
    },
    {
      firstName: "Pandora",
      lastName: "Douris",
      street: "04 Farragut Crossing",
      city: "Bezons",
      zipCode: "95874 CEDEX",
      birthDate: "16/01/1963",
      startDate: "14/02/2023",
      department: "Engineering",
      state: "Île-de-France",
    },
    {
      firstName: "Gracie",
      lastName: "Wybourne",
      street: "2 Sherman Pass",
      city: "La Roche-sur-Yon",
      zipCode: "85009 CEDEX",
      birthDate: "07/07/1996",
      startDate: "11/12/2022",
      department: "Sales",
      state: "Pays de la Loire",
    },
    {
      firstName: "Palmer",
      lastName: "Caslett",
      street: "82 Tennessee Center",
      city: "Boulogne-Billancourt",
      zipCode: "92645 CEDEX",
      birthDate: "26/10/1983",
      startDate: "19/05/2023",
      department: "Engineering",
      state: "Île-de-France",
    },
    {
      firstName: "Konstantine",
      lastName: "Boule",
      street: "975 Longview Avenue",
      city: "Altkirch",
      zipCode: "68134 CEDEX",
      birthDate: "01/04/1972",
      startDate: "02/04/2023",
      department: "Human Resources",
      state: "Alsace",
    },
    {
      firstName: "Uri",
      lastName: "Werndley",
      street: "418 Lyons Terrace",
      city: "Vaulx-en-Velin",
      zipCode: "69519 CEDEX",
      birthDate: "31/12/1969",
      startDate: "20/02/2023",
      department: "Human Resources",
      state: "Rhône-Alpes",
    },
    {
      firstName: "Sibylla",
      lastName: "Brake",
      street: "29121 Rockefeller Avenue",
      city: "Les Sables-d'Olonne",
      zipCode: "85109 CEDEX",
      birthDate: "26/02/1971",
      startDate: "02/01/2023",
      department: "Legal",
      state: "Pays de la Loire",
    },
    {
      firstName: "Christina",
      lastName: "Grinley",
      street: "64 Merrick Road",
      city: "Nantes",
      zipCode: "44101 CEDEX 4",
      birthDate: "18/04/1990",
      startDate: "12/02/2023",
      department: "Marketing",
      state: "Pays de la Loire",
    },
    {
      firstName: "Johannes",
      lastName: "Josupeit",
      street: "7 Havey Way",
      city: "Lillers",
      zipCode: "62193 CEDEX",
      birthDate: "09/09/1997",
      startDate: "03/10/2022",
      department: "Marketing",
      state: "Nord-Pas-de-Calais",
    },
    {
      firstName: "Mikol",
      lastName: "Mateescu",
      street: "69687 Melrose Court",
      city: "Paris La Défense",
      zipCode: "92907 CEDEX",
      birthDate: "26/12/2005",
      startDate: "28/04/2023",
      department: "Marketing",
      state: "Île-de-France",
    },
    {
      firstName: "Anastasie",
      lastName: "Haighton",
      street: "8631 North Junction",
      city: "Paris 12",
      zipCode: "75609 CEDEX 12",
      birthDate: "02/02/1966",
      startDate: "09/02/2023",
      department: "Human Resources",
      state: "Île-de-France",
    },
    {
      firstName: "Rad",
      lastName: "Withey",
      street: "3 David Alley",
      city: "Reims",
      zipCode: "51571 CEDEX 2",
      birthDate: "14/03/2001",
      startDate: "11/04/2023",
      department: "Engineering",
      state: "Champagne-Ardenne",
    },
    {
      firstName: "Jessie",
      lastName: "Brockest",
      street: "57 Ohio Drive",
      city: "Carcassonne",
      zipCode: "11878 CEDEX 9",
      birthDate: "11/07/1963",
      startDate: "30/09/2022",
      department: "Legal",
      state: "Languedoc-Roussillon",
    },
    {
      firstName: "Claudianus",
      lastName: "Davoren",
      street: "1661 Linden Lane",
      city: "Parthenay",
      zipCode: "79204 CEDEX",
      birthDate: "19/04/1998",
      startDate: "25/08/2022",
      department: "Engineering",
      state: "Poitou-Charentes",
    },
    {
      firstName: "Olva",
      lastName: "Annesley",
      street: "429 Fordem Point",
      city: "Paris 06",
      zipCode: "75270 CEDEX 06",
      birthDate: "20/08/1978",
      startDate: "31/07/2023",
      department: "Marketing",
      state: "Île-de-France",
    },
    {
      firstName: "Jennee",
      lastName: "Cucuzza",
      street: "031 Lerdahl Park",
      city: "Fontenay-sous-Bois",
      zipCode: "94726 CEDEX",
      birthDate: "16/08/1988",
      startDate: "10/12/2022",
      department: "Sales",
      state: "Île-de-France",
    },
    {
      firstName: "Vernor",
      lastName: "Benion",
      street: "8 Banding Court",
      city: "Meaux",
      zipCode: "77109 CEDEX",
      birthDate: "01/11/2006",
      startDate: "02/01/2023",
      department: "Engineering",
      state: "Île-de-France",
    },
    {
      firstName: "Amie",
      lastName: "Harmer",
      street: "78762 Nancy Center",
      city: "Paris 15",
      zipCode: "75902 CEDEX 15",
      birthDate: "15/07/1979",
      startDate: "31/10/2022",
      department: "Engineering",
      state: "Île-de-France",
    },
    {
      firstName: "Stephanus",
      lastName: "MacCrachen",
      street: "61 Main Plaza",
      city: "Saint-Jean-de-Luz",
      zipCode: "64504 CEDEX",
      birthDate: "19/07/1967",
      startDate: "06/04/2023",
      department: "Human Resources",
      state: "Aquitaine",
    },
    {
      firstName: "Maryjane",
      lastName: "Bavridge",
      street: "5 Duke Way",
      city: "Avignon",
      zipCode: "84902 CEDEX 9",
      birthDate: "28/08/1991",
      startDate: "11/03/2023",
      department: "Marketing",
      state: "Provence-Alpes-Côte d'Azur",
    },
    {
      firstName: "Trixi",
      lastName: "Currey",
      street: "39143 American Ash Plaza",
      city: "Toulon",
      zipCode: "83092 CEDEX",
      birthDate: "24/09/1996",
      startDate: "26/06/2023",
      department: "Legal",
      state: "Provence-Alpes-Côte d'Azur",
    },
    {
      firstName: "Tobe",
      lastName: "Neiland",
      street: "87 Grasskamp Court",
      city: "Roissy Charles-de-Gaulle",
      zipCode: "95761 CEDEX 1",
      birthDate: "03/06/1961",
      startDate: "14/06/2023",
      department: "Engineering",
      state: "Île-de-France",
    },
    {
      firstName: "Giordano",
      lastName: "Skae",
      street: "2 Badeau Place",
      city: "Montigny-lès-Metz",
      zipCode: "57954 CEDEX",
      birthDate: "04/03/1979",
      startDate: "18/05/2023",
      department: "Sales",
      state: "Lorraine",
    },
    {
      firstName: "Ree",
      lastName: "Robbey",
      street: "639 Gateway Point",
      city: "Grenoble",
      zipCode: "38014 CEDEX 1",
      birthDate: "20/11/2005",
      startDate: "09/08/2023",
      department: "Legal",
      state: "Rhône-Alpes",
    },
    {
      firstName: "Hubie",
      lastName: "Cufflin",
      street: "14 Pearson Point",
      city: "Houilles",
      zipCode: "78804 CEDEX",
      birthDate: "03/10/1986",
      startDate: "17/05/2023",
      department: "Legal",
      state: "Île-de-France",
    },
    {
      firstName: "Jonathon",
      lastName: "Frusher",
      street: "93040 Corben Junction",
      city: "Mende",
      zipCode: "48005 CEDEX",
      birthDate: "21/04/1981",
      startDate: "16/08/2022",
      department: "Engineering",
      state: "Languedoc-Roussillon",
    },
    {
      firstName: "Elmo",
      lastName: "Tiron",
      street: "08635 Prairie Rose Way",
      city: "Évry",
      zipCode: "91009 CEDEX",
      birthDate: "08/09/1984",
      startDate: "09/01/2023",
      department: "Human Resources",
      state: "Île-de-France",
    },
    {
      firstName: "Ashlen",
      lastName: "Trusse",
      street: "330 Warbler Street",
      city: "Troyes",
      zipCode: "10606 CEDEX",
      birthDate: "28/11/1961",
      startDate: "28/02/2023",
      department: "Human Resources",
      state: "Champagne-Ardenne",
    },
    {
      firstName: "Adriena",
      lastName: "Baglin",
      street: "86 Oak Avenue",
      city: "Manosque",
      zipCode: "04104 CEDEX",
      birthDate: "13/12/1974",
      startDate: "27/02/2023",
      department: "Engineering",
      state: "Provence-Alpes-Côte d'Azur",
    },
    {
      firstName: "Malena",
      lastName: "Baulch",
      street: "11432 Fuller Avenue",
      city: "Nîmes",
      zipCode: "30904 CEDEX 9",
      birthDate: "28/04/1984",
      startDate: "07/05/2023",
      department: "Human Resources",
      state: "Languedoc-Roussillon",
    },
    {
      firstName: "Dawn",
      lastName: "Oxe",
      street: "26709 Walton Pass",
      city: "Pont-à-Mousson",
      zipCode: "54704 CEDEX",
      birthDate: "24/03/1980",
      startDate: "11/06/2023",
      department: "Engineering",
      state: "Lorraine",
    },
    {
      firstName: "Roman",
      lastName: "Cormack",
      street: "408 Bunker Hill Avenue",
      city: "Lyon",
      zipCode: "69446 CEDEX 03",
      birthDate: "26/01/1993",
      startDate: "07/03/2023",
      department: "Sales",
      state: "Rhône-Alpes",
    },
    {
      firstName: "Shermy",
      lastName: "Lewendon",
      street: "8 Nova Way",
      city: "Marseille",
      zipCode: "13298 CEDEX 20",
      birthDate: "02/06/2000",
      startDate: "31/07/2023",
      department: "Sales",
      state: "Provence-Alpes-Côte d'Azur",
    },
    {
      firstName: "Cam",
      lastName: "Kunkler",
      street: "27 Gale Terrace",
      city: "Firminy",
      zipCode: "42704 CEDEX",
      birthDate: "11/09/2003",
      startDate: "10/06/2023",
      department: "Legal",
      state: "Rhône-Alpes",
    },
    {
      firstName: "Eberhard",
      lastName: "Kleinmann",
      street: "174 Homewood Terrace",
      city: "Paris 01",
      zipCode: "75032 CEDEX 01",
      birthDate: "18/04/1973",
      startDate: "05/05/2023",
      department: "Engineering",
      state: "Île-de-France",
    },
    {
      firstName: "Elva",
      lastName: "Mish",
      street: "10 Scoville Parkway",
      city: "Ivry-sur-Seine",
      zipCode: "94857 CEDEX",
      birthDate: "04/10/1984",
      startDate: "12/06/2023",
      department: "Marketing",
      state: "Île-de-France",
    },
    {
      firstName: "Emilee",
      lastName: "Itscowics",
      street: "1 Washington Crossing",
      city: "Crépy-en-Valois",
      zipCode: "60804 CEDEX",
      birthDate: "17/03/1966",
      startDate: "09/11/2022",
      department: "Human Resources",
      state: "Picardie",
    },
    {
      firstName: "Brena",
      lastName: "Entres",
      street: "43829 Westridge Avenue",
      city: "Aix-en-Provence",
      zipCode: "13592 CEDEX 3",
      birthDate: "19/07/2009",
      startDate: "20/10/2022",
      department: "Legal",
      state: "Provence-Alpes-Côte d'Azur",
    },
    {
      firstName: "Steven",
      lastName: "Blaymires",
      street: "05 Glacier Hill Court",
      city: "Aix-en-Provence",
      zipCode: "13617 CEDEX 1",
      birthDate: "11/10/2002",
      startDate: "24/08/2022",
      department: "Legal",
      state: "Provence-Alpes-Côte d'Azur",
    },
    {
      firstName: "Grantley",
      lastName: "Lushey",
      street: "38 Shasta Pass",
      city: "Oyonnax",
      zipCode: "01117 CEDEX",
      birthDate: "01/10/1994",
      startDate: "24/03/2023",
      department: "Engineering",
      state: "Rhône-Alpes",
    },
    {
      firstName: "Eduardo",
      lastName: "Bisatt",
      street: "1002 Trailsway Junction",
      city: "Ajaccio",
      zipCode: "20311 CEDEX 1",
      birthDate: "07/01/1994",
      startDate: "02/08/2023",
      department: "Sales",
      state: "Corse",
    },
    {
      firstName: "Maitilde",
      lastName: "Stegell",
      street: "4 Jenifer Circle",
      city: "Strasbourg",
      zipCode: "67024 CEDEX 1",
      birthDate: "20/01/1988",
      startDate: "13/04/2023",
      department: "Engineering",
      state: "Alsace",
    },
    {
      firstName: "Penrod",
      lastName: "Freestone",
      street: "7 Utah Terrace",
      city: "Périgny",
      zipCode: "17189 CEDEX",
      birthDate: "30/03/2009",
      startDate: "05/07/2023",
      department: "Engineering",
      state: "Poitou-Charentes",
    },
    {
      firstName: "Claus",
      lastName: "Bicheno",
      street: "97 Forest Run Crossing",
      city: "Rennes",
      zipCode: "35087 CEDEX",
      birthDate: "18/06/1972",
      startDate: "24/08/2022",
      department: "Legal",
      state: "Bretagne",
    },
    {
      firstName: "Opalina",
      lastName: "Tremontana",
      street: "7 Dexter Circle",
      city: "Rueil-Malmaison",
      zipCode: "92848 CEDEX",
      birthDate: "30/11/1987",
      startDate: "02/09/2022",
      department: "Marketing",
      state: "Île-de-France",
    },
    {
      firstName: "Ernestine",
      lastName: "Barge",
      street: "28 Clarendon Court",
      city: "Lillers",
      zipCode: "62193 CEDEX",
      birthDate: "19/10/1974",
      startDate: "13/01/2023",
      department: "Human Resources",
      state: "Nord-Pas-de-Calais",
    },
    {
      firstName: "Riordan",
      lastName: "Glencrosche",
      street: "33700 Merrick Avenue",
      city: "Argenteuil",
      zipCode: "95109 CEDEX",
      birthDate: "04/11/1961",
      startDate: "07/04/2023",
      department: "Sales",
      state: "Île-de-France",
    },
    {
      firstName: "Louisa",
      lastName: "McJerrow",
      street: "377 Brown Lane",
      city: "Marne-la-Vallée",
      zipCode: "77427 CEDEX 2",
      birthDate: "25/03/2010",
      startDate: "25/09/2022",
      department: "Engineering",
      state: "Île-de-France",
    },
    {
      firstName: "Francklin",
      lastName: "Wager",
      street: "604 Onsgard Circle",
      city: "Sophia Antipolis",
      zipCode: "06905 CEDEX",
      birthDate: "04/08/2007",
      startDate: "06/05/2023",
      department: "Engineering",
      state: "Provence-Alpes-Côte d'Azur",
    },
    {
      firstName: "Elene",
      lastName: "Twentyman",
      street: "89 Bunker Hill Avenue",
      city: "Longwy",
      zipCode: "54412 CEDEX",
      birthDate: "09/07/1995",
      startDate: "30/12/2022",
      department: "Marketing",
      state: "Lorraine",
    },
    {
      firstName: "Samuele",
      lastName: "Birtonshaw",
      street: "8408 Springs Street",
      city: "Lyon",
      zipCode: "69281 CEDEX 01",
      birthDate: "16/07/1985",
      startDate: "10/07/2023",
      department: "Human Resources",
      state: "Rhône-Alpes",
    },
    {
      firstName: "Tyler",
      lastName: "Pumphreys",
      street: "723 Upham Terrace",
      city: "Tourcoing",
      zipCode: "59208 CEDEX",
      birthDate: "27/12/2001",
      startDate: "04/11/2022",
      department: "Marketing",
      state: "Nord-Pas-de-Calais",
    },
    {
      firstName: "Erna",
      lastName: "Denty",
      street: "5 Commercial Hill",
      city: "Marne-la-Vallée",
      zipCode: "77427 CEDEX 2",
      birthDate: "26/03/1981",
      startDate: "23/11/2022",
      department: "Engineering",
      state: "Île-de-France",
    },
    {
      firstName: "Nannette",
      lastName: "Haigh",
      street: "963 Ridgeview Lane",
      city: "Bonneuil-sur-Marne",
      zipCode: "94384 CEDEX",
      birthDate: "24/02/2005",
      startDate: "10/02/2023",
      department: "Legal",
      state: "Île-de-France",
    },
    {
      firstName: "Joachim",
      lastName: "Worgen",
      street: "5 Corry Center",
      city: "Perpignan",
      zipCode: "66921 CEDEX",
      birthDate: "23/01/1968",
      startDate: "17/07/2023",
      department: "Engineering",
      state: "Languedoc-Roussillon",
    },
    {
      firstName: "Raffaello",
      lastName: "Royall",
      street: "83837 Magdeline Way",
      city: "Saint-Priest",
      zipCode: "69794 CEDEX",
      birthDate: "14/09/2006",
      startDate: "20/02/2023",
      department: "Marketing",
      state: "Rhône-Alpes",
    },
    {
      firstName: "Jerry",
      lastName: "Duley",
      street: "3 Pine View Road",
      city: "Hénin-Beaumont",
      zipCode: "62254 CEDEX",
      birthDate: "13/01/1962",
      startDate: "13/07/2023",
      department: "Engineering",
      state: "Nord-Pas-de-Calais",
    },
    {
      firstName: "Willie",
      lastName: "Rimer",
      street: "413 Lotheville Street",
      city: "Laval",
      zipCode: "53009 CEDEX",
      birthDate: "22/03/1993",
      startDate: "10/10/2022",
      department: "Engineering",
      state: "Pays de la Loire",
    },
    {
      firstName: "Tamiko",
      lastName: "Hucks",
      street: "99152 Oneill Alley",
      city: "Blagnac",
      zipCode: "31709 CEDEX",
      birthDate: "03/10/1973",
      startDate: "20/10/2022",
      department: "Marketing",
      state: "Midi-Pyrénées",
    },
    {
      firstName: "Abram",
      lastName: "Bodycombe",
      street: "50626 Pine View Terrace",
      city: "Rivesaltes",
      zipCode: "66605 CEDEX",
      birthDate: "27/11/1965",
      startDate: "03/08/2023",
      department: "Sales",
      state: "Languedoc-Roussillon",
    },
    {
      firstName: "Rycca",
      lastName: "Covendon",
      street: "19 Service Crossing",
      city: "Poitiers",
      zipCode: "86020 CEDEX",
      birthDate: "24/11/1977",
      startDate: "21/07/2023",
      department: "Human Resources",
      state: "Poitou-Charentes",
    },
    {
      firstName: "Konstantin",
      lastName: "Dowall",
      street: "942 Barnett Park",
      city: "Villejuif",
      zipCode: "94804 CEDEX",
      birthDate: "09/10/1977",
      startDate: "08/10/2022",
      department: "Sales",
      state: "Île-de-France",
    },
    {
      firstName: "Cybil",
      lastName: "Ratcliff",
      street: "9705 Rusk Place",
      city: "Nantes",
      zipCode: "44958 CEDEX 9",
      birthDate: "06/09/2002",
      startDate: "15/08/2022",
      department: "Sales",
      state: "Pays de la Loire",
    },
    {
      firstName: "Gaye",
      lastName: "Beaver",
      street: "0225 Bultman Lane",
      city: "Marseille",
      zipCode: "13348 CEDEX 20",
      birthDate: "09/02/1986",
      startDate: "24/05/2023",
      department: "Engineering",
      state: "Provence-Alpes-Côte d'Azur",
    },
    {
      firstName: "Giraldo",
      lastName: "Andrioletti",
      street: "3744 Novick Center",
      city: "Paris 06",
      zipCode: "75270 CEDEX 06",
      birthDate: "21/05/2001",
      startDate: "01/05/2023",
      department: "Engineering",
      state: "Île-de-France",
    },
    {
      firstName: "Vanni",
      lastName: "Rieflin",
      street: "91 Westridge Place",
      city: "Carpiquet",
      zipCode: "14654 CEDEX",
      birthDate: "13/12/1979",
      startDate: "09/06/2023",
      department: "Marketing",
      state: "Basse-Normandie",
    },
    {
      firstName: "Mercie",
      lastName: "Sherratt",
      street: "54 Blue Bill Park Point",
      city: "Hénin-Beaumont",
      zipCode: "62254 CEDEX",
      birthDate: "13/04/1985",
      startDate: "19/10/2022",
      department: "Marketing",
      state: "Nord-Pas-de-Calais",
    },
    {
      firstName: "Ellsworth",
      lastName: "Clerk",
      street: "47416 Esker Terrace",
      city: "Corbeil-Essonnes",
      zipCode: "91815 CEDEX",
      birthDate: "19/08/1987",
      startDate: "11/02/2023",
      department: "Marketing",
      state: "Île-de-France",
    },
    {
      firstName: "Phelia",
      lastName: "Liddard",
      street: "96400 Fisk Pass",
      city: "Charenton-le-Pont",
      zipCode: "94224 CEDEX",
      birthDate: "22/07/1999",
      startDate: "20/02/2023",
      department: "Marketing",
      state: "Île-de-France",
    },
    {
      firstName: "Newton",
      lastName: "Leeson",
      street: "831 Sauthoff Pass",
      city: "Massy",
      zipCode: "91881 CEDEX",
      birthDate: "13/02/2007",
      startDate: "05/02/2023",
      department: "Legal",
      state: "Île-de-France",
    },
    {
      firstName: "Norry",
      lastName: "Spileman",
      street: "672 Little Fleur Crossing",
      city: "Versailles",
      zipCode: "78020 CEDEX",
      birthDate: "26/10/1982",
      startDate: "21/07/2023",
      department: "Human Resources",
      state: "Île-de-France",
    },
  ],
};

/**
 *
 * @param {*} state Qui sera initialisé avec "initialState"
 * @param {*} action
 * @returns
 */
function reducer(state = initialState, action) {
  switch (action.type) {
    case "AJOUTER_EMPLOYEE":
      return { ...state, employees: [...state.employees, action.employee] };
    default:
      return state;
  }
}

export const store = createStore(reducer, compose(ReactReduxDevTools));
